services:
  db:
    image: postgres:16-alpine
    container_name: conquest-postgres
    restart: always
    environment:
      POSTGRES_DB: conquest_db
      POSTGRES_USER: conquest_dev
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5432:5432"
    volumes:
      - conquest-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.2
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${USERNAME_KEYCLOAK:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${PASSWORD_KEYCLOAK:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/conquest_db
      KC_DB_USERNAME: ${DB_USERNAME:-conquest_dev}
      KC_DB_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-theme/conquest:/opt/keycloak/themes/conquest
    depends_on:
      - db



  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: conquest-api
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/conquest_db
  #     SPRING_DATASOURCE_USERNAME: conquest_dev
  #     SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}
  #   depends_on:
  #     - db


volumes:
  conquest-db-data: